#!/bin/bash
# Sticker Bot One-Liner Installer
# Usage: curl -sSL https://raw.githubusercontent.com/ZanardiZZ/sticker-bot/main/install.sh | bash

set -e

echo "🤖 Sticker Bot Installer v1.0"
echo "=============================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Detect OS
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    OS="linux"
    echo -e "${GREEN}✓${NC} Detected OS: Linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    OS="macos"
    echo -e "${GREEN}✓${NC} Detected OS: macOS"
else
    echo -e "${RED}❌ Unsupported OS: $OSTYPE${NC}"
    echo "   This installer supports Linux and macOS only."
    echo "   For Windows, see: https://github.com/ZanardiZZ/sticker-bot#windows"
    exit 1
fi

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js not found${NC}"
    echo ""
    echo "Please install Node.js 20+ first:"
    if [[ "$OS" == "linux" ]]; then
        echo "  Ubuntu/Debian: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs"
        echo "  Or use nvm: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
    elif [[ "$OS" == "macos" ]]; then
        echo "  Via Homebrew: brew install node@20"
        echo "  Or download: https://nodejs.org/"
    fi
    exit 1
fi

NODE_VERSION=$(node -v | cut -d 'v' -f 2 | cut -d '.' -f 1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${RED}❌ Node.js 20+ required${NC}"
    echo "   Current version: $(node -v)"
    echo "   Please upgrade Node.js to version 20 or higher"
    exit 1
fi

echo -e "${GREEN}✓${NC} Node.js $(node -v)"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}❌ npm not found${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} npm $(npm -v)"

# Check git
if ! command -v git &> /dev/null; then
    echo -e "${YELLOW}⚠${NC}  git not found, will download tarball instead"
    USE_GIT=false
else
    echo -e "${GREEN}✓${NC} git $(git --version | cut -d ' ' -f 3)"
    USE_GIT=true
fi

echo ""

# Installation directory
INSTALL_DIR="${1:-$HOME/sticker-bot}"

# Check if directory exists
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}⚠${NC}  Directory already exists: $INSTALL_DIR"
    read -p "   Remove and reinstall? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "   Removing existing directory..."
        rm -rf "$INSTALL_DIR"
    else
        echo "   Installation cancelled"
        exit 0
    fi
fi

echo -e "${BLUE}📁 Installing to:${NC} $INSTALL_DIR"
echo ""

# Download
echo -e "${BLUE}📥 Downloading Sticker Bot...${NC}"

if [ "$USE_GIT" = true ]; then
    git clone --depth 1 https://github.com/ZanardiZZ/sticker-bot.git "$INSTALL_DIR"
else
    # Fallback: download tarball
    mkdir -p "$INSTALL_DIR"
    curl -sSL https://github.com/ZanardiZZ/sticker-bot/archive/refs/heads/main.tar.gz | tar -xz -C "$INSTALL_DIR" --strip-components=1
fi

cd "$INSTALL_DIR"

echo -e "${GREEN}✓${NC} Downloaded successfully"
echo ""

# Install dependencies
echo -e "${BLUE}📦 Installing dependencies...${NC}"
echo "   This may take a few minutes..."
echo ""

npm ci --silent --no-progress 2>&1 | grep -v "npm WARN" || true

echo -e "${GREEN}✓${NC} Dependencies installed"
echo ""

# Create minimal .env for setup mode
SETUP_TOKEN="$(openssl rand -hex 24)"
SESSION_SECRET="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 32)"
cat > .env << EOF
# Auto-generated by installer - disable SETUP_WIZARD_ENABLED after setup
PORT=3000
SETUP_MODE=true
SETUP_WIZARD_ENABLED=true
SETUP_WIZARD_TOKEN=$SETUP_TOKEN
SESSION_SECRET=$SESSION_SECRET
JWT_SECRET=$JWT_SECRET
EOF
chmod 600 .env

echo -e "${GREEN}✓${NC} Created initial configuration"
echo ""

# Start web server in background
echo -e "${BLUE}🚀 Starting setup wizard...${NC}"
echo ""

# Trap to cleanup on exit
trap 'kill $WEB_PID 2>/dev/null' EXIT

# Start server
npm run web > setup.log 2>&1 &
WEB_PID=$!

echo "   Server PID: $WEB_PID"
echo "   Waiting for server to start..."

# Wait for server to be ready (max 30 seconds)
SECONDS=0
MAX_WAIT=30
while [ $SECONDS -lt $MAX_WAIT ]; do
    if curl -s http://localhost:3000 > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} Server is ready!"
        break
    fi
    sleep 1
done

if [ $SECONDS -ge $MAX_WAIT ]; then
    echo -e "${RED}❌ Server failed to start${NC}"
    echo "   Check logs: tail -f $INSTALL_DIR/setup.log"
    exit 1
fi

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                       ║${NC}"
echo -e "${GREEN}║  ${BLUE}✨  Setup Wizard Ready!${GREEN}                           ║${NC}"
echo -e "${GREEN}║                                                       ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BLUE}→${NC} Open in your browser:"
echo -e "    ${YELLOW}http://localhost:3000/setup?token=$SETUP_TOKEN${NC}"
echo ""
echo -e "  ${BLUE}→${NC} Or scan this URL with your phone:"
LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
echo -e "    ${YELLOW}http://${LAN_IP}:3000/setup?token=$SETUP_TOKEN${NC}"
echo ""
echo -e "  ${YELLOW}Keep this token private. It expires after setup is finalized.${NC}"
echo ""
echo -e "  ${BLUE}→${NC} Logs: ${YELLOW}tail -f $INSTALL_DIR/setup.log${NC}"
echo ""

# Try to open browser
if command -v xdg-open &> /dev/null; then
    echo "   Opening browser..."
    xdg-open "http://localhost:3000/setup?token=$SETUP_TOKEN" 2>/dev/null || true
elif command -v open &> /dev/null; then
    echo "   Opening browser..."
    open "http://localhost:3000/setup?token=$SETUP_TOKEN" 2>/dev/null || true
fi

echo ""
echo -e "${BLUE}Press Ctrl+C when you're done with the setup wizard${NC}"
echo ""

# Wait for user to finish
wait $WEB_PID
